"""add folders

Revision ID: 798fba75ae6d
Revises: bd21150ee165
Create Date: 2026-09-15 06:39:41.849744+00:00
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "798fba75ae6d"
down_revision: str | None = "bd21150ee165"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "folders",
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("color", sa.String(length=30), server_default=sa.text("'lime'"), nullable=False),
        sa.Column("position", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_folders_owner_id_users"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["folders.id"],
            name=op.f("fk_folders_parent_id_folders"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_folders")),
    )
    op.create_index(op.f("ix_folders_owner_id"), "folders", ["owner_id"], unique=False)
    op.create_index(
        "ix_folders_owner_id_parent_id_position",
        "folders",
        ["owner_id", "parent_id", "position"],
        unique=False,
    )
    op.add_column("study_sets", sa.Column("folder_id", sa.Uuid(), nullable=True))
    op.create_index(op.f("ix_study_sets_folder_id"), "study_sets", ["folder_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_study_sets_folder_id_folders"),
        "study_sets",
        "folders",
        ["folder_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_study_sets_folder_id_folders"), "study_sets", type_="foreignkey")
    op.drop_index(op.f("ix_study_sets_folder_id"), table_name="study_sets")
    op.drop_column("study_sets", "folder_id")
    op.drop_index("ix_folders_owner_id_parent_id_position", table_name="folders")
    op.drop_index(op.f("ix_folders_owner_id"), table_name="folders")
    op.drop_table("folders")
    # ### end Alembic commands ###
