"""baseline

Revision ID: 5dbb0a6127ae
Revises: 
Create Date: 2026-09-08 08:05:44.279567+00:00
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '5dbb0a6127ae'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
