"""add battles

Revision ID: battles
Revises: google_oauth
Create Date: 2026-10-05 06:14:18.223291+00:00
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "battles"
down_revision: str | None = "google_oauth"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("ALTER TYPE studymode ADD VALUE IF NOT EXISTS 'battle'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "battles",
        sa.Column("creator_id", sa.Uuid(), nullable=False),
        sa.Column("set_id", sa.Uuid(), nullable=False),
        sa.Column("request_key", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "waiting",
                "countdown",
                "active",
                "finished",
                "cancelled",
                "expired",
                name="battlestatus",
            ),
            server_default=sa.text("'waiting'"),
            nullable=False,
        ),
        sa.Column(
            "direction",
            postgresql.ENUM("term_to_def", "def_to_term", name="studydirection", create_type=False),
            nullable=False,
        ),
        sa.Column("question_count", sa.Integer(), nullable=False),
        sa.Column("questions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deadline_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("winner_id", sa.Uuid(), nullable=True),
        sa.Column(
            "finish_reason",
            sa.Enum("completed", "timeout", name="battlefinishreason"),
            nullable=True,
        ),
        sa.Column("rematch_of_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "question_count BETWEEN 4 AND 20", name=op.f("ck_battles_question_count_range")
        ),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["users.id"],
            name=op.f("fk_battles_creator_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["rematch_of_id"],
            ["battles.id"],
            name=op.f("fk_battles_rematch_of_id_battles"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["set_id"],
            ["study_sets.id"],
            name=op.f("fk_battles_set_id_study_sets"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["winner_id"],
            ["users.id"],
            name=op.f("fk_battles_winner_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_battles")),
        sa.UniqueConstraint("creator_id", "request_key", name="uq_battles_creator_request_key"),
    )
    op.create_index(op.f("ix_battles_creator_id"), "battles", ["creator_id"], unique=False)
    op.create_index(op.f("ix_battles_rematch_of_id"), "battles", ["rematch_of_id"], unique=False)
    op.create_index(op.f("ix_battles_set_id"), "battles", ["set_id"], unique=False)
    op.create_index(
        "ix_battles_set_id_created_at", "battles", ["set_id", "created_at"], unique=False
    )
    op.create_index(op.f("ix_battles_winner_id"), "battles", ["winner_id"], unique=False)
    op.create_table(
        "battle_participants",
        sa.Column("battle_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("slot", sa.Integer(), nullable=False),
        sa.Column(
            "joined_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("ready_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("answered_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("correct_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("slot BETWEEN 1 AND 2", name=op.f("ck_battle_participants_slot_range")),
        sa.ForeignKeyConstraint(
            ["battle_id"],
            ["battles.id"],
            name=op.f("fk_battle_participants_battle_id_battles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_battle_participants_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_battle_participants")),
        sa.UniqueConstraint("battle_id", "slot", name="uq_battle_participants_battle_slot"),
        sa.UniqueConstraint("battle_id", "user_id", name="uq_battle_participants_battle_user"),
    )
    op.create_index(
        op.f("ix_battle_participants_battle_id"), "battle_participants", ["battle_id"], unique=False
    )
    op.create_index(
        op.f("ix_battle_participants_user_id"), "battle_participants", ["user_id"], unique=False
    )
    op.create_table(
        "battle_answers",
        sa.Column("participant_id", sa.Uuid(), nullable=False),
        sa.Column("question_id", sa.String(length=120), nullable=False),
        sa.Column("client_answer_id", sa.Uuid(), nullable=False),
        sa.Column("value", sa.String(length=4000), nullable=False),
        sa.Column("correct", sa.Boolean(), nullable=False),
        sa.Column(
            "answered_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["participant_id"],
            ["battle_participants.id"],
            name=op.f("fk_battle_answers_participant_id_battle_participants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_battle_answers")),
        sa.UniqueConstraint(
            "participant_id", "client_answer_id", name="uq_battle_answers_participant_client"
        ),
        sa.UniqueConstraint(
            "participant_id", "question_id", name="uq_battle_answers_participant_question"
        ),
    )
    op.create_index(
        op.f("ix_battle_answers_participant_id"), "battle_answers", ["participant_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_battle_answers_participant_id"), table_name="battle_answers")
    op.drop_table("battle_answers")
    op.drop_index(op.f("ix_battle_participants_user_id"), table_name="battle_participants")
    op.drop_index(op.f("ix_battle_participants_battle_id"), table_name="battle_participants")
    op.drop_table("battle_participants")
    op.drop_index(op.f("ix_battles_winner_id"), table_name="battles")
    op.drop_index("ix_battles_set_id_created_at", table_name="battles")
    op.drop_index(op.f("ix_battles_set_id"), table_name="battles")
    op.drop_index(op.f("ix_battles_rematch_of_id"), table_name="battles")
    op.drop_index(op.f("ix_battles_creator_id"), table_name="battles")
    op.drop_table("battles")
    op.execute("DROP TYPE battlefinishreason")
    op.execute("DROP TYPE battlestatus")
    op.execute("DELETE FROM reviews WHERE mode = 'battle'")
    op.execute("ALTER TYPE studymode RENAME TO studymode_old")
    op.execute("CREATE TYPE studymode AS ENUM ('flashcards', 'learn', 'test', 'write', 'listen')")
    op.execute("ALTER TABLE reviews ALTER COLUMN mode TYPE studymode USING mode::text::studymode")
    op.execute(
        "ALTER TABLE study_sessions ALTER COLUMN mode TYPE studymode USING mode::text::studymode"
    )
    op.execute("DROP TYPE studymode_old")
    # ### end Alembic commands ###
