"""course publication

Revision ID: 588d5e7de756
Revises: 076576f4b655
Create Date: 2026-09-16 04:42:17.265767+00:00
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "588d5e7de756"
down_revision: str | None = "076576f4b655"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "courses",
        sa.Column("is_published", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    op.add_column("courses", sa.Column("published_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column(
        "courses",
        sa.Column(
            "moderation_status", sa.String(length=20), server_default="pending", nullable=False
        ),
    )
    op.add_column(
        "courses",
        sa.Column(
            "tags",
            postgresql.ARRAY(sa.String(length=60)),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
    op.create_check_constraint(
        "ck_courses_moderation_status",
        "courses",
        "moderation_status IN ('pending', 'ok', 'blocked')",
    )


def downgrade() -> None:
    op.drop_constraint("ck_courses_moderation_status", "courses", type_="check")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("courses", "tags")
    op.drop_column("courses", "moderation_status")
    op.drop_column("courses", "published_at")
    op.drop_column("courses", "is_published")
    # ### end Alembic commands ###
