"""add answer strictness setting

Revision ID: 99f82c234c5f
Revises: 324b5a5eb5c9
Create Date: 2026-09-15 08:29:10.448785+00:00
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '99f82c234c5f'
down_revision: str | None = '324b5a5eb5c9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('answer_strictness', sa.String(length=10), server_default=sa.text("'moderate'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'answer_strictness')
    # ### end Alembic commands ###
