"""add study engine

Revision ID: 324b5a5eb5c9
Revises: e1b5ddeb6bd1
Create Date: 2026-09-15 07:44:25.573836+00:00
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '324b5a5eb5c9'
down_revision: str | None = 'e1b5ddeb6bd1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_sessions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('set_id', sa.Uuid(), nullable=False),
    sa.Column('mode', sa.Enum('flashcards', 'learn', 'test', 'write', 'listen', name='studymode'), nullable=False),
    sa.Column('status', sa.Enum('active', 'finished', 'abandoned', name='sessionstatus'), server_default=sa.text("'active'"), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cards_seen', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('cards_correct', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['set_id'], ['study_sets.id'], name=op.f('fk_study_sessions_set_id_study_sets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_study_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_study_sessions'))
    )
    op.create_index(op.f('ix_study_sessions_set_id'), 'study_sessions', ['set_id'], unique=False)
    op.create_index(op.f('ix_study_sessions_user_id'), 'study_sessions', ['user_id'], unique=False)
    op.create_index('ix_study_sessions_user_id_set_id_status', 'study_sessions', ['user_id', 'set_id', 'status'], unique=False)
    op.create_table('user_set_progress',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('set_id', sa.Uuid(), nullable=False),
    sa.Column('mastered_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('learning_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('not_started_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('mastery_percent', sa.Float(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_studied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['set_id'], ['study_sets.id'], name=op.f('fk_user_set_progress_set_id_study_sets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_set_progress_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_set_progress')),
    sa.UniqueConstraint('user_id', 'set_id', name='uq_user_set_progress_user_id_set_id')
    )
    op.create_index(op.f('ix_user_set_progress_set_id'), 'user_set_progress', ['set_id'], unique=False)
    op.create_index(op.f('ix_user_set_progress_user_id'), 'user_set_progress', ['user_id'], unique=False)
    op.create_table('card_states',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('card_id', sa.Uuid(), nullable=False),
    sa.Column('set_id', sa.Uuid(), nullable=False),
    sa.Column('direction', sa.Enum('term_to_def', 'def_to_term', name='studydirection'), nullable=False),
    sa.Column('state', sa.Enum('new', 'learning', 'review', 'relearning', name='cardstatekind'), server_default=sa.text("'new'"), nullable=False),
    sa.Column('stability', sa.Float(), nullable=True),
    sa.Column('difficulty', sa.Float(), nullable=True),
    sa.Column('step', sa.Integer(), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reps', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('lapses', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('elapsed_days', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('scheduled_days', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('suspended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduler_version', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], name=op.f('fk_card_states_card_id_cards'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['set_id'], ['study_sets.id'], name=op.f('fk_card_states_set_id_study_sets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_card_states_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_card_states')),
    sa.UniqueConstraint('user_id', 'card_id', 'direction', name='uq_card_states_user_id_card_id_direction')
    )
    op.create_index(op.f('ix_card_states_card_id'), 'card_states', ['card_id'], unique=False)
    op.create_index(op.f('ix_card_states_set_id'), 'card_states', ['set_id'], unique=False)
    op.create_index(op.f('ix_card_states_user_id'), 'card_states', ['user_id'], unique=False)
    op.create_index('ix_card_states_user_id_due_at_active', 'card_states', ['user_id', 'due_at'], unique=False, postgresql_where=sa.text('suspended_at IS NULL'))
    op.create_index('ix_card_states_user_id_set_id_state', 'card_states', ['user_id', 'set_id', 'state'], unique=False)
    op.create_table('reviews',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('card_id', sa.Uuid(), nullable=False),
    sa.Column('set_id', sa.Uuid(), nullable=False),
    sa.Column('direction', sa.Enum('term_to_def', 'def_to_term', name='studydirection'), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('client_review_id', sa.Uuid(), nullable=False),
    sa.Column('mode', sa.Enum('flashcards', 'learn', 'test', 'write', 'listen', name='studymode'), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('answer_correct', sa.Boolean(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('state_before', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('state_after', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('scheduler_version', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('rating BETWEEN 1 AND 4', name=op.f('ck_reviews_rating_range')),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], name=op.f('fk_reviews_card_id_cards'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['study_sessions.id'], name=op.f('fk_reviews_session_id_study_sessions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['set_id'], ['study_sets.id'], name=op.f('fk_reviews_set_id_study_sets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_reviews_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviews')),
    sa.UniqueConstraint('user_id', 'client_review_id', name='uq_reviews_user_id_client_review_id')
    )
    op.create_index('ix_reviews_card_id_direction', 'reviews', ['card_id', 'direction'], unique=False)
    op.create_index(op.f('ix_reviews_session_id'), 'reviews', ['session_id'], unique=False)
    op.create_index(op.f('ix_reviews_user_id'), 'reviews', ['user_id'], unique=False)
    op.create_index('ix_reviews_user_id_reviewed_at', 'reviews', ['user_id', 'reviewed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reviews_user_id_reviewed_at', table_name='reviews')
    op.drop_index(op.f('ix_reviews_user_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_session_id'), table_name='reviews')
    op.drop_index('ix_reviews_card_id_direction', table_name='reviews')
    op.drop_table('reviews')
    op.drop_index('ix_card_states_user_id_set_id_state', table_name='card_states')
    op.drop_index('ix_card_states_user_id_due_at_active', table_name='card_states', postgresql_where=sa.text('suspended_at IS NULL'))
    op.drop_index(op.f('ix_card_states_user_id'), table_name='card_states')
    op.drop_index(op.f('ix_card_states_set_id'), table_name='card_states')
    op.drop_index(op.f('ix_card_states_card_id'), table_name='card_states')
    op.drop_table('card_states')
    op.drop_index(op.f('ix_user_set_progress_user_id'), table_name='user_set_progress')
    op.drop_index(op.f('ix_user_set_progress_set_id'), table_name='user_set_progress')
    op.drop_table('user_set_progress')
    op.drop_index('ix_study_sessions_user_id_set_id_status', table_name='study_sessions')
    op.drop_index(op.f('ix_study_sessions_user_id'), table_name='study_sessions')
    op.drop_index(op.f('ix_study_sessions_set_id'), table_name='study_sessions')
    op.drop_table('study_sessions')
    op.execute('DROP TYPE cardstatekind')
    op.execute('DROP TYPE studydirection')
    op.execute('DROP TYPE sessionstatus')
    op.execute('DROP TYPE studymode')
    # ### end Alembic commands ###
