"""add bot links and durable events

Revision ID: 45df4942a2bd
Revises: 4600403f3abd
Create Date: 2026-09-17 02:31:18.283326+00:00
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '45df4942a2bd'
down_revision: str | None = '4600403f3abd'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_events',
    sa.Column('platform', sa.String(length=16), nullable=False),
    sa.Column('event_id', sa.String(length=128), nullable=False),
    sa.Column('actor_id', sa.String(length=32), nullable=False),
    sa.Column('command', sa.String(length=16), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=True),
    sa.Column('callback_id', sa.String(length=128), nullable=True),
    sa.Column('reply', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('lease_token', sa.Uuid(), nullable=True),
    sa.Column('available_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bot_events')),
    sa.UniqueConstraint('platform', 'event_id', name=op.f('uq_bot_events_platform'))
    )
    op.create_index('ix_bot_events_delivery', 'bot_events', ['platform', 'status', 'available_at'], unique=False)
    op.create_table('bot_link_codes',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('platform', sa.String(length=16), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_bot_link_codes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bot_link_codes')),
    sa.UniqueConstraint('code_hash', name=op.f('uq_bot_link_codes_code_hash'))
    )
    op.create_table('bot_links',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('platform', sa.String(length=16), nullable=False),
    sa.Column('actor_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_bot_links_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bot_links')),
    sa.UniqueConstraint('platform', 'actor_id', name=op.f('uq_bot_links_platform')),
    sa.UniqueConstraint('user_id', 'platform', name=op.f('uq_bot_links_user_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bot_links')
    op.drop_table('bot_link_codes')
    op.drop_index('ix_bot_events_delivery', table_name='bot_events')
    op.drop_table('bot_events')
    # ### end Alembic commands ###
