"""add tts cache and usage counters

Revision ID: 6f89ed6c80b1
Revises: d0e5a3b9f962
Create Date: 2026-09-15 08:43:24.310143+00:00
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '6f89ed6c80b1'
down_revision: str | None = 'd0e5a3b9f962'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usage_counters',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('metric', sa.String(length=32), nullable=False),
    sa.Column('period_key', sa.String(length=10), nullable=False),
    sa.Column('value', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_usage_counters_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usage_counters')),
    sa.UniqueConstraint('user_id', 'metric', 'period_key', name='uq_usage_counters_user_id_metric_period_key')
    )
    op.create_index(op.f('ix_usage_counters_user_id'), 'usage_counters', ['user_id'], unique=False)
    op.create_table('tts_cache',
    sa.Column('text_hash', sa.String(length=64), nullable=False),
    sa.Column('lang', sa.String(length=10), nullable=False),
    sa.Column('voice', sa.String(length=32), nullable=False),
    sa.Column('speed', sa.Float(), server_default=sa.text('1.0'), nullable=False),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('media_asset_id', sa.Uuid(), nullable=False),
    sa.Column('hits', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['media_asset_id'], ['media_assets.id'], name=op.f('fk_tts_cache_media_asset_id_media_assets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tts_cache')),
    sa.UniqueConstraint('text_hash', name='uq_tts_cache_text_hash')
    )
    op.create_index('ix_tts_cache_lang_voice', 'tts_cache', ['lang', 'voice'], unique=False)
    op.create_index(op.f('ix_tts_cache_media_asset_id'), 'tts_cache', ['media_asset_id'], unique=False)
    op.create_index(op.f('ix_tts_cache_text_hash'), 'tts_cache', ['text_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tts_cache_text_hash'), table_name='tts_cache')
    op.drop_index(op.f('ix_tts_cache_media_asset_id'), table_name='tts_cache')
    op.drop_index('ix_tts_cache_lang_voice', table_name='tts_cache')
    op.drop_table('tts_cache')
    op.drop_index(op.f('ix_usage_counters_user_id'), table_name='usage_counters')
    op.drop_table('usage_counters')
    # ### end Alembic commands ###
