"""add study sets and cards

Revision ID: bd21150ee165
Revises: c71d8e4a930f
Create Date: 2026-09-15 06:29:25.401399+00:00
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "bd21150ee165"
down_revision: str | None = "c71d8e4a930f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "study_sets",
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("description", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column(
            "visibility",
            sa.Enum("private", "unlisted", "public", name="setvisibility"),
            server_default=sa.text("'private'"),
            nullable=False,
        ),
        sa.Column("slug", sa.String(length=200), nullable=False),
        sa.Column(
            "lang_term", sa.String(length=10), server_default=sa.text("'ru'"), nullable=False
        ),
        sa.Column(
            "lang_definition", sa.String(length=10), server_default=sa.text("'ru'"), nullable=False
        ),
        sa.Column("cards_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("copied_from_id", sa.Uuid(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["copied_from_id"],
            ["study_sets.id"],
            name=op.f("fk_study_sets_copied_from_id_study_sets"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            name=op.f("fk_study_sets_owner_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_study_sets")),
    )
    op.create_index(op.f("ix_study_sets_deleted_at"), "study_sets", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_study_sets_owner_id"), "study_sets", ["owner_id"], unique=False)
    op.create_index(
        "ix_study_sets_owner_id_deleted_at", "study_sets", ["owner_id", "deleted_at"], unique=False
    )
    op.create_index(op.f("ix_study_sets_slug"), "study_sets", ["slug"], unique=True)
    op.create_table(
        "cards",
        sa.Column("set_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("term", sa.Text(), nullable=False),
        sa.Column("definition", sa.Text(), nullable=False),
        sa.Column("term_transcription", sa.String(length=300), nullable=True),
        sa.Column("definition_transcription", sa.String(length=300), nullable=True),
        sa.Column("hint", sa.String(length=1000), nullable=True),
        sa.Column(
            "content_type",
            sa.Enum("text", "latex", "code", name="contenttype"),
            server_default=sa.text("'text'"),
            nullable=False,
        ),
        sa.Column("code_language", sa.String(length=50), nullable=True),
        sa.Column(
            "alt_answers",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["set_id"],
            ["study_sets.id"],
            name=op.f("fk_cards_set_id_study_sets"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cards")),
    )
    op.create_index(op.f("ix_cards_set_id"), "cards", ["set_id"], unique=False)
    op.create_index("ix_cards_set_id_position", "cards", ["set_id", "position"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_cards_set_id_position", table_name="cards")
    op.drop_index(op.f("ix_cards_set_id"), table_name="cards")
    op.drop_table("cards")
    op.drop_index(op.f("ix_study_sets_slug"), table_name="study_sets")
    op.drop_index("ix_study_sets_owner_id_deleted_at", table_name="study_sets")
    op.drop_index(op.f("ix_study_sets_owner_id"), table_name="study_sets")
    op.drop_index(op.f("ix_study_sets_deleted_at"), table_name="study_sets")
    op.drop_table("study_sets")
    op.execute("DROP TYPE IF EXISTS contenttype")
    op.execute("DROP TYPE IF EXISTS setvisibility")
    # ### end Alembic commands ###
