"""add card images

Revision ID: e1b5ddeb6bd1
Revises: 798fba75ae6d
Create Date: 2026-09-15 07:13:03.624684+00:00
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'e1b5ddeb6bd1'
down_revision: str | None = '798fba75ae6d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_assets',
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('image', 'audio', name='mediakind'), nullable=False),
    sa.Column('s3_key', sa.String(length=500), nullable=False),
    sa.Column('mime', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('source', sa.Enum('upload', 'tts', name='mediasource'), server_default=sa.text("'upload'"), nullable=False),
    sa.Column('status', sa.Enum('pending', 'ready', 'rejected', name='mediastatus'), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_media_assets_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media_assets')),
    sa.UniqueConstraint('s3_key', name=op.f('uq_media_assets_s3_key'))
    )
    op.create_index('ix_media_assets_owner_id_checksum', 'media_assets', ['owner_id', 'checksum'], unique=False)
    op.create_index('ix_media_assets_owner_id_kind_status', 'media_assets', ['owner_id', 'kind', 'status'], unique=False)
    op.add_column('cards', sa.Column('term_image_id', sa.Uuid(), nullable=True))
    op.add_column('cards', sa.Column('definition_image_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_cards_definition_image_id'), 'cards', ['definition_image_id'], unique=False)
    op.create_index(op.f('ix_cards_term_image_id'), 'cards', ['term_image_id'], unique=False)
    op.create_foreign_key(op.f('fk_cards_definition_image_id_media_assets'), 'cards', 'media_assets', ['definition_image_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_cards_term_image_id_media_assets'), 'cards', 'media_assets', ['term_image_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_cards_term_image_id_media_assets'), 'cards', type_='foreignkey')
    op.drop_constraint(op.f('fk_cards_definition_image_id_media_assets'), 'cards', type_='foreignkey')
    op.drop_index(op.f('ix_cards_term_image_id'), table_name='cards')
    op.drop_index(op.f('ix_cards_definition_image_id'), table_name='cards')
    op.drop_column('cards', 'definition_image_id')
    op.drop_column('cards', 'term_image_id')
    op.drop_index('ix_media_assets_owner_id_kind_status', table_name='media_assets')
    op.drop_index('ix_media_assets_owner_id_checksum', table_name='media_assets')
    op.drop_table('media_assets')
    op.execute('DROP TYPE mediastatus')
    op.execute('DROP TYPE mediasource')
    op.execute('DROP TYPE mediakind')
    # ### end Alembic commands ###
