"""migrate legacy public sets to courses

Revision ID: 736162040e0e
Revises: 588d5e7de756
Create Date: 2026-09-16 05:02:02.189810+00:00
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "736162040e0e"
down_revision: str | None = "588d5e7de756"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "courses",
        sa.Column("is_listed", sa.Boolean(), server_default=sa.text("true"), nullable=False),
    )
    # ### end Alembic commands ###
    backfill_legacy_courses(op.get_bind())


def backfill_legacy_courses(connection: sa.Connection) -> None:
    # Пустые старые публикации сохраняем: миграция не должна ломать выданные ссылки.
    # «По ссылке» остаётся вне индекса и будущего каталога.
    connection.execute(
        sa.text("""
        WITH candidates AS MATERIALIZED (
            SELECT s.*, gen_random_uuid() AS course_id, gen_random_uuid() AS section_id,
                   gen_random_uuid() AS article_id
            FROM study_sets s
            WHERE s.deleted_at IS NULL AND s.visibility IN ('public', 'unlisted')
              AND NOT EXISTS (SELECT 1 FROM course_articles a WHERE a.set_id = s.id)
        ), inserted_courses AS (
            INSERT INTO courses (id, owner_id, title, description, slug, is_published,
                                 is_listed, published_at, moderation_status, tags)
            SELECT course_id, owner_id, title, description, 'course-' || course_id::text,
                   true, visibility = 'public', created_at, 'pending', '{}'
            FROM candidates RETURNING id
        ), inserted_sections AS (
            INSERT INTO course_sections (id, course_id, title, position)
            SELECT c.section_id, c.course_id, 'Основной раздел', 0
            FROM candidates c JOIN inserted_courses nc ON nc.id = c.course_id
            RETURNING id
        )
        INSERT INTO course_articles (id, section_id, set_id, title, body, position)
        SELECT c.article_id, c.section_id, c.id, c.title, '', 0
        FROM candidates c JOIN inserted_sections ns ON ns.id = c.section_id
    """)
    )


def downgrade() -> None:
    # Не удаляем созданные курсы: после миграции автор уже мог их отредактировать.
    # Старый код не умеет скрывать курс от индекса — не расширяем доступ при откате.
    op.execute("UPDATE courses SET is_published = false WHERE is_listed = false")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("courses", "is_listed")
    # ### end Alembic commands ###
