"""allow platform owned media

Revision ID: 40c48e5c50a4
Revises: 6f89ed6c80b1
Create Date: 2026-09-15 08:44:24.268258+00:00
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '40c48e5c50a4'
down_revision: str | None = '6f89ed6c80b1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('media_assets', 'owner_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('media_assets', 'owner_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
