"""add study progress reset timestamp

Revision ID: 78b91a0a2a0b
Revises: 004c33b0c117
Create Date: 2026-09-16 06:09:21.368629+00:00
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "78b91a0a2a0b"
down_revision: str | None = "004c33b0c117"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_set_progress", sa.Column("reset_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_set_progress", "reset_at")
    # ### end Alembic commands ###
